services:
  app:
    image: golang:latest
    container_name: goencomenda
    volumes:
      - $C:\Users\37022091\workspace\uninassau\Wellignton\encomendas-api
    working_dir: /app
    command: go run main.go
    ports:
      - "8080:8080"
  
  mysql_db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: encomendas
    ports:
      - "3306:3306"